### ISSUE TITLE
Basecalling Filtering Assembly

### ISSUE THREAD

**Issue by cmkim1** [logcossin/ForReport#1]
Basecalling 후에 통계 확인하는 절차입니다.
`NanoStat` 함수가 없어서 막혀 있는 상황이에요.

생략하고 `NanoFIlt` 도 해봤는데 안됐습니다.

`cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ NanoStat --fastq barcod17.fastq
NanoStat: command not found
`
콘다를 다시 다운 받아볼까요

-> 서버에서 제 아이디에 다운 받아서 해결 됐습니다

**Comment by cmkim1** [comment]
`NanoStat` `flye` 둘다 `apt_pkg` 라는 모듈이 없다고 뜨고 진행이 안되고 있습니다.

```python
cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ NanoStat --fastq barcode17.fastq
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
``` 


```python
cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ flye --nano-hq barcode17.fastq -o barcod12 -i 2 -t 10
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

**Comment by cmkim1** [comment]
네 `(base)` 라고 뜹니다.

```
cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ conda activate
(base) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ cat barcode17_output/pass/* > barcode17.fastq
(base) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ activate ont
(base) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ NanoStat --fastq barcode17.fastq
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

**Comment by logcossin** [comment]
conda activate ont 하시고 괄호가 (ont)로 바뀌면 다시 실행해 보세요
