### ISSUE TITLE
QC

### ISSUE THREAD

**Issue by cmkim1** [logcossin/ForReport#2]
`busco` 다운로드

```
(ont) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ conda install -c bioconda busco
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                         

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
``` 

qc 파일 생성
```
(ont) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ busco -m genome -i barcode17_q13.fastq --out barcode17_q13_qc --out_path assembly_qc -c 18 -l bacteria
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```
busco가 다운 안된 것 처럼 나옵니다.

**Comment by logcossin** [comment]
(ont) 환경에 busco 설치 시 충돌이 나는 거 같아 새로 (busco) 환경을 만드는 것으로 변경했습니다.

cmkim 계정에 설치해두었으니 새로 설치하실 필요는 없습니다.

**Comment by cmkim1** [comment]
```
(busco) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ busco -m genome -i barcode17_q13 --out barcode17_q13_qc --out_path assembly_qc -c 17 -l bacteria
2023-07-03 15:09:36 INFO:	***** Start a BUSCO v5.4.7 analysis, current time: 07/03/2023 15:09:36 *****
2023-07-03 15:09:36 INFO:	Configuring BUSCO with local environment
2023-07-03 15:09:36 INFO:	Mode is genome
2023-07-03 15:09:36 ERROR:	A run with the name /leafeon/analysis1/cmkim/abalone_gut_ont/assembly_qc/barcode17_q13_qc already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
2023-07-03 15:09:36 ERROR:	BUSCO analysis failed!
2023-07-03 15:09:36 ERROR:	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues
```
-f 를 추가해서 다시 돌려봤습니다.

```
(busco) cmkim@leafeon:/leafeon/analysis1/cmkim/abalone_gut_ont$ busco -m genome -i barcode17_q13 --out barcode17_q13_qc --out_path assembly_qc -c 17 -l bacteria -f
2023-07-03 15:12:14 INFO:	***** Start a BUSCO v5.4.7 analysis, current time: 07/03/2023 15:12:14 *****
2023-07-03 15:12:14 INFO:	Configuring BUSCO with local environment
2023-07-03 15:12:14 INFO:	Mode is genome
2023-07-03 15:12:14 INFO:	'Force' option selected; overwriting previous results directory
2023-07-03 15:12:14 INFO:	Downloading information on latest versions of BUSCO data...
2023-07-03 15:12:20 INFO:	Running in batch mode. 12 input files found in /leafeon/analysis1/cmkim/abalone_gut_ont/barcode17_q13
2023-07-03 15:12:20 INFO:	Input file is /leafeon/analysis1/cmkim/abalone_gut_ont/barcode17_q13/10-consensus
2023-07-03 15:12:20 CRITICAL:	Unhandled exception occurred:
Traceback (most recent call last):
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/BuscoRunner.py", line 148, in run
    self.runner = AnalysisRunner(self.config)
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/BuscoRunner.py", line 360, in __init__
    self.analysis = analysis_type()
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/analysis/GenomeAnalysis.py", line 90, in __init__
    super().__init__()
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/analysis/GenomeAnalysis.py", line 46, in __init__
    super().__init__()
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/analysis/Analysis.py", line 21, in __init__
    if not self.check_nucleotide_file(self.input_file):
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/busco/analysis/Analysis.py", line 27, in check_nucleotide_file
    for record in SeqIO.parse(filename, "fasta"):
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 223, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/cmkim/miniconda3/envs/busco/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 45, in __init__
    self.stream = open(source, "r" + mode)
IsADirectoryError: [Errno 21] Is a directory: '/leafeon/analysis1/cmkim/abalone_gut_ont/barcode17_q13/10-consensus'


2023-07-03 15:12:20 ERROR:	[Errno 21] Is a directory: '/leafeon/analysis1/cmkim/abalone_gut_ont/barcode17_q13/10-consensus'
2023-07-03 15:12:20 ERROR:	BUSCO analysis failed!
2023-07-03 15:12:20 ERROR:	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

```

여전히 에러가 나옵니다. `2023-07-03 15:12:20 CRITICAL:	Unhandled exception occurred:` 이 부분이 문제인 것 같은데 어
떻게 해결할 수 있을까요?
